# Testing setup for Apache Kafka.

version: '3.9'

services:

  
  orders_db: 
    image: mysql
    ports: 
      - "3308:3306"
    expose:
      # Opens port 3306 on the container
      - 3308
    container_name: orders_db
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: order_db
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_ROOT_PASSWORD: admin 
    volumes:
      - /orders-db:/var/lib/mysql   
    networks:
      - orders
  
  products_db:
    container_name: products_db
    image: mysql:5.7
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: products_db
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_ROOT_PASSWORD: admin
    ports:
      - '3310:3306'
    expose:
      # Opens port 3306 on the container
      - '3310'
      # Where our data will be persisted
    volumes:
      - ./data/products-db:/var/lib/mysql


networks:
  default:
      driver: bridge
  keycloak-and-mysql-network:
  products:
  orders:

volumes:
  orders-db:
  products-db: